### ISSUE TITLE
Problème affichage

### ISSUE THREAD

**Issue by oct45** [llegoff/Pi400VGA#1]
J'ai un problème avec l'affichage, j'ai copié collé correctement l'exemple dans le config.txt, l'image s'affiche au démarrage (écran arc en ciel + le curseur clignote) puis plus aucun signal.

**Comment by llegoff** [comment]
Bonsoir,
Sur quel OS ?  raspberry pi OS 32bits ou 64bits ? ou autre ?

**Comment by oct45** [comment]
J'ai d'abord utilisé la version 64 bits puis la version 32 bits : sans succès

**Comment by llegoff** [comment]
Bonjour,

je vois que dans la dernière version de raspberry pi OS, le pilote d'affichage KMS est chargé dans le config.txt , au lieu du FKMS auparavant  

essayez en remplaçant les lignes 

#Enable DRM vc4 V3D driver
dtoverlay=vc4-kms-v3d
maxframebuffer=2

par 

#Enable DRM vc4 V3D driver
dtoverlay=vc4-fkms-v3d
maxframebuffer=2

**Comment by oct45** [comment]
Cela a bien fonctionné merci, seul problème maintenant quand je mets la résolution de mon écran (1440x900) l'image est décalé à droite et semble écraser, dans des résolutions plus basses pas de soucis

**Comment by llegoff** [comment]
Pour la résolution 1440x900, il faut la config suivante dans le fichier config.txt
dpi_group=2
dpi_mode=47

le port vga est un port analogique, les écran LCD effectuent une numérisation du signal, et effectuent une calibration pour détecter les limite de l'image, si la calibration automatique se fait lors du boot quand l'écran est noir, elle peut mal détecté les bord de l'image. il faut alors la relancer dans le menu de l'écran.

**Comment by oct45** [comment]
J'utilise pourtant ces réglages et je refais manuellement la calibration de l'écran et rien n'y fait, en dpi_mode 28 ça fonctionne par contre c'est une basse résolution

**Comment by llegoff** [comment]
dpi_mode=46 pour la résolution 1440x900 à 60hz (reduced blanking)
dpi_mode=47 pour la résolution 1440x900 à 60hz 
dpi_mode=48 pour la résolution 1440x900 à 75hz 
dpi_mode=49 pour la résolution 1440x900 à 85hz 
dpi_mode=50 pour la résolution 1440x900 à 120hz (reduced blanking)

https://www.raspberrypi.com/documentation/computers/config_txt.html#hdmi-mode

**Comment by oct45** [comment]
Avec le 46 au lieu du 47 ça fonctionne parfaitement encore merci
